CC=cl65

2bpp:
	$(CC) -O -o EXAMPLE2.PRG -t cx16 main-2bpp.c

run2bpp:
	../x16emu/x16emu -prg EXAMPLE2.PRG -run

4bpp:
	$(CC) -O -o EXAMPLE4.PRG -t cx16 main-4bpp.c

run4bpp:
	../x16emu/x16emu -prg EXAMPLE4.PRG -run

8bpp:
	$(CC) -O -o EXAMPLE8.PRG -t cx16 main-8bpp.c

run8bpp:
	../x16emu/x16emu -prg EXAMPLE8.PRG -run